import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

const Layout = ({title,children}) => {
  return (
    <>
     <Head>
        <title>{title ? title + '-Amazona' : "Amazona"}</title>
        <meta name="description" content="Generated by summit" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


     <div className="flex min-h-screen flex-col justify-between bg-cyan-200">
        <header>
            <nav className='flex justify-between items-center h-12 shadow-md bg-gray-200 z-100 px-4'>
                <Link href="/">
                <a className='text-lg font-bold'>Amazona</a>
                </Link>
                <div >
                    <Link href="/cart">Cart </Link>
                    <Link href="/login"><a className='p-2' >Login</a></Link>
                </div>
            </nav>
        </header>
        <main className='container m-auto mt-4 px-4'>
            {children}
        </main>
        <footer className='flex justify-center items-center font-bold h-10 shadow-inner z-50 bg-gray-100'>
            footer
        </footer>
     </div>
    </>
   
  )
}

export default Layout